config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'complaint/new'
  post 'complaint/add'
  get 'complaint/history'
  get 'complaint/active'
  get 'complaint/archive'
  post 'complaint/decline'
  post 'complaint/reply'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'user/profile'

  post 'user/rec_destroy' => 'user#rec_destroy', :as => 'rec_destroy'

  root 'start#show'

  get 'start/show' => 'start#show'

  get 'join' => 'join#show'

  get 'join/service' => 'join#service', :as => 'service'

  get 'join/act' => 'join#act', :as => 'act'

  get 'join/club' => 'join#club', :as => 'club'

  get 'join/calendar' => 'join#calendar', :as => 'calendar'

  post 'join/write' => 'join#write', :as => 'write'

  get 'coach/timetable'

  post 'coach/coach_rec_destroy' => 'coach#coach_rec_destroy', :as => 'coach_rec_destroy' 

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_records, dependent: :destroy
  has_many :calendar_records, through: :user_records
  has_one :coach
  has_one :employee
  has_many :complaints

  validates :name, presence: { message: 'не может быть пустым' }
  validates :name, format: { with: /\A([a-zа-яё0-9]+(\s)?)+\z/i, message: 'должно быть строкой' }
  # validates_uniqueness_of :email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/user_controller.rb
# frozen_string_literal: true

# user
class UserController < ApplicationController
  before_action :authenticate_user!

  def profile
    @coach = Coach.find_by(user_id: current_user&.id)
    @employee = Employee.find_by(user_id: current_user&.id)
    case 
    when @coach.present?
      @status = t('profile.сoach')
    when @employee.present?
      @status = t('profile.employee')
    else
      @status = t('profile.student')
    end
  end

  def rec_destroy
    @my_id = rec_destroy_params[:my_id]
    UserRecord.find_by(calendar_record_id: @my_id, user: current_user).destroy
  end

  private

  def rec_destroy_params
    params.permit(:my_id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  # sessions
  class SessionsController < Devise::SessionsController
    # POST /resource/sign_in
    # rubocop:disable Metrics/AbcSize
    def create
      user = User.find_for_authentication(email: params[:user][:email])
      if user.present? && user&.valid_password?(params[:user][:password])
        resource = warden.authenticate!(scope: resource_name, recall: 'new')
        session['resource_email'] = resource.email
        session['resource_name'] = resource.name
        flash[:notice] = "#{t('session.create.welcome')}, #{session['resource_name']}!"
        sign_in_and_redirect(resource_name, resource)
      else
        render 'layouts/incorrect'
      end
    end
    # rubocop:enable Metrics/AbcSize

    # DELETE /resource/sign_out
    def destroy
      name = current_user.name.clone
      super
      flash[:notice] = "#{t('session.destroy.come_back')}, #{name}!"
    end
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/user/_student.html.erb
<h6><% if UserRecord.find_by(user: current_user).present?%></h6>
            <% arr = []%>
                <%CalendarRecord.joins(user_records: :user).where("user_id = ?", current_user.id).each do |r|%>
                    <% my_start = r.start_time.strftime("%H:%M") %> 
                    <% my_end = r.end_time.strftime("%H:%M") %>
                    <% my_date = r.start_time.strftime("%d-%m-%Y")%>
                    <% to_push = []%>
                    <% to_push[0] = r.coach.act.service.name%>
                    <% to_push[1] = r.coach.act.activity%>
                    <% to_push[2] = r.club.name%>
                    <% to_push[3] = r.coach.name%>
                    <% to_push[4] = my_date%>
                    <% to_push[5] = my_start%>
                    <% to_push[6] = my_end%>
                    <% to_push[7] = r.id%>
                    
                    <%# to_push=[r.coach.act.service.name, r.coach.act.activity, r.club.name, r.coach.name, my_date,
                            my_start + '-' + my_end]%>
                    <% arr.push(to_push)%>
                <%end%>
                <%arr.sort_by!{|serv, act, club, coach, date, t_start, t_end, my_id| [date, t_start]}%>
                <ol>
                    <% arr.each do |my_r|%>
                        <div id="id<%=my_r[7]%>" style='margin-left: 50px'>
                            <li>
                                Услуги: <%= my_r[0]%> <br>
                                Занятие: <%= my_r[1]%> <br>
                                Клуб: <%= my_r[2] %> <br>
                                Тренер: <%= my_r[3]%> <br>
                                Дата: <%=my_r[4]%> <br>
                                Время: <%= my_r[5]+ '-' + my_r[6]%>
                            </li>
                            <%= form_with url: rec_destroy_path do |f|%>
                                <%= f.hidden_field :my_id, :value => my_r[7]%>
                                <% cancel = t('profile.cancel')%>
                                <%= f.submit(cancel, class: "btn btn-danger")%>
                            <% end %> 
                            <br>
                        </div>
                    <%end%>                
                </ol>
        <% else %> <h3 style='margin-left: 50px'> У вас еще нет записей </h3>
        <% end %>

app/views/user/profile.html.erb
<div id='profile'>
    <div class="row justify-content-between">
        <h3 style="display:flex; justify-content:center;"><strong><%=t('profile.my')%><br><br></strong></h3>
        <div class='col-6'>        
        <h3 style='margin-left: 50px'><%=t('profile.name')%>: <%= current_user.name%><h3>
        <h3 style='margin-left: 50px'><%=t('profile.email')%>: <%= current_user.email%><h3> <br>
        <h3 style='margin-left: 50px'><%=t('profile.status')%>: <%= @status %> <h3>

        <% if @coach.present?%>
            <h3 style='margin-left: 50px'><%=t('profile.spec')%>: <%= @coach.act.service.name%> => <%=@coach.act.activity%> <h3>
        <% elsif @employee.nil? %>
            <h3 style='margin-left: 50px'><%=t('profile.my_recs')%>:<h3>        
            <%= render 'user/student' %>
        <% end %>
        </div>
        <div class='col-5'>
            <%= image_tag "profile.png", width: '500', height: '400',:alt => "Профиль"%>
        </div>
    </div>
</div>

app/views/user/rec_destroy.turbo_stream.erb
<turbo-stream action="remove" target="id<%=@my_id%>">
</turbo-stream>