config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'complaint/new'
  post 'complaint/add'
  get 'complaint/history'
  get 'complaint/active'
  get 'complaint/archive'
  post 'complaint/decline'
  post 'complaint/reply'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'user/profile'

  post 'user/rec_destroy' => 'user#rec_destroy', :as => 'rec_destroy'

  root 'start#show'

  get 'start/show' => 'start#show'

  get 'join' => 'join#show'

  get 'join/service' => 'join#service', :as => 'service'

  get 'join/act' => 'join#act', :as => 'act'

  get 'join/club' => 'join#club', :as => 'club'

  get 'join/calendar' => 'join#calendar', :as => 'calendar'

  post 'join/write' => 'join#write', :as => 'write'

  get 'coach/timetable'

  post 'coach/coach_rec_destroy' => 'coach#coach_rec_destroy', :as => 'coach_rec_destroy' 

end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user
  belongs_to :employee, optional: true

  enum status: [:process, :success, :fail]

  validates :message, presence: { message: 'не может быть пустым' }
  validates :status, presence: { message: 'не может быть пустым' }
  validates :theme, presence: { message: 'не может быть пустым' }

  def dif_valid?
    errors.add(:user_id, "are the same") if Employee.find_by(user_id: user_id)
    p Employee.find_by(user_id: user_id)
  end

  validate :dif_valid?
end

app/controllers/complaint_controller.rb
class ComplaintController < ApplicationController
  before_action :authenticate_user!
  before_action :not_employee, only: %w[active archive]
  before_action :if_employee, only: %w[new history]

  def new
  end

  def add
    @theme = new_params[:theme]
    @problem = new_params[:problem]
    Complaint.create!(user: current_user, theme: @theme, message: @problem, status: 0)
    redirect_to complaint_history_path 
  end

  def history
  end

  def active
    @status = lambda do |user|
        coach = Coach.find_by(user_id: user)
        employee = Employee.find_by(user_id: user)
        case 
        when coach.present?
            status = t('profile.сoach')
        when @employee.present?
            status = t('profile.employee')
        else
            status = t('profile.student')
        end
        status    
    end
  end

    def reply
        @comp_id = reply_params[:comp_id]
        @reply = reply_params[:reply]
        Complaint.find_by(id: @comp_id).update(status: 1, response: @reply, employee_id: Employee.find_by(user_id: current_user.id).id)
    end

    def decline
        @comp_id = decline_params[:comp_id]
        Complaint.find_by(id: @comp_id).update(status: 2)        
    end

    def archive
        @status = lambda do |user|
            coach = Coach.find_by(user_id: user)
            employee = Employee.find_by(user_id: user)
            case 
            when coach.present?
                status = t('profile.сoach')
            when @employee.present?
                status = t('profile.employee')
            else
                status = t('profile.student')
            end
            status    
        end
    end

  private

  def new_params
    params.permit(:theme, :problem)
  end

  def decline_params
    params.permit(:comp_id)
  end

  def reply_params
    params.permit(:comp_id, :reply)
  end

  def not_employee
    redirect_to root_path if Employee.find_by(user_id: current_user&.id).nil?
  end

  def if_employee
    redirect_to root_path if Employee.find_by(user_id: current_user&.id).present?
  end
end

app/helpers/complaint_helper.rb
module ComplaintHelper
end

app/views/complaint/active.html.erb
<div style="margin-left: 50px">
    <h2><%= t('header.active_complaints') %></h2> <br>
    <% if Complaint.find_by(status: 0).present?%>
        <ol>     
        <% Complaint.where(status: 0).each do |comp|%>             
            <div class="card" style="font-size:20px; width:700px" id="comp<%= comp.id %>">
                <div class="card-body">
                    <div style='display:flex; justify-content: space-between;'>
                        <div> <%= comp.created_at.strftime("%d.%m.%Y") + ' ' + comp.created_at.strftime("%H:%M")%> </div>
                        <%= form_with url: complaint_decline_path do |f|%>
                            <%= f.hidden_field :comp_id, :value => comp.id%>
                            <%= f.submit('Отклонить жалобу', class: "btn btn-danger", id:"decl")%>
                        <% end %> 
                    </div>
                    <p style="margin-left: 50px;">Имя: <%=comp.user.name%></p> 
                    <p style="margin-left: 50px;">E-mail: <%=comp.user.email%></p>
                    <p style="margin-left: 50px;">Статус: <%= @status.call(comp.user) %></p>  
                    <p style="margin-left: 50px;">Тема: <%=comp.theme%></p>
                    <p style="margin-left: 50px;"><strong>Жалоба: </strong><%=comp.message%></p>

                    <%= form_with url: complaint_reply_path do |f|%>
                        <div style="margin-left: 50px; width:550px;">
                            <%= f.hidden_field :comp_id, :value => comp.id%>
                            <strong>Ответ: </strong><%= f.text_area :reply, :rows => 3, class: "form-control", autofocus: true %><br>
                            <%= f.submit('Отправить', class: "btn btn-primary", id:"send")%>
                        </div>
                    <%end%>  
                </div>
            </div>
        <% end %>
        </ol>
    <%else %>
        <h3> Нет активных жалоб </h3>
    <%end%>
</div>

app/views/complaint/archive.html.erb
<div style="margin-left: 50px">
    <h2><%= t('header.archive_complaints') %></h2> <br>
    <% if Complaint.find_by(status: 1).present? || Complaint.find_by(status: 2).present?%>
        <ol>     
        <% Complaint.where('status>?', 0).each do |comp|%>             
            <div class="card" style="font-size:20px; width:700px" id="comp<%= comp.id %>">
                <div class="card-body">
                    <div style='display:flex; justify-content: space-between;'>
                        <div> <%= comp.created_at.strftime("%d.%m.%Y") + ' ' + comp.created_at.strftime("%H:%M")%> </div>
                    </div>
                    <p style="margin-left: 50px"><strong>Статус жалобы: </strong><%=t("complaint.new.#{comp.status}")%></p>
                    <p style="margin-left: 50px;"><strong>Имя: </strong><%=comp.user.name%></p> 
                    <p style="margin-left: 50px;"><strong>E-mail: </strong><%=comp.user.email%></p>
                    <p style="margin-left: 50px;"><strong>Статус: </strong><%= @status.call(comp.user) %></p>  
                    <p style="margin-left: 50px;"><strong>Тема: </strong><%=comp.theme%></p>
                    <p style="margin-left: 50px;"><strong>Жалоба: </strong><%=comp.message%></p>
                    <% if comp.response.present? %>
                        <br>
                        
                        <p><%=comp.updated_at.strftime("%d.%m.%Y") + ' ' + comp.updated_at.strftime("%H:%M")%></p>
                        <%p comp%>
                        <p style="margin-left: 50px;"><strong>Сотрудник: </strong><%=comp.employee.user.name%></p>
                        <p style="margin-left: 50px;"> <strong>Ответ: </strong><%=comp.response%></p>   
                    <% end %>                     
                </div>
            </div>
        <% end %>
        </ol>
    <%else %>
        <h3> Нет архивных жалоб </h3>
    <%end%>
</div>

app/views/complaint/decline.turbo_stream.erb
<turbo-stream action="remove" target="comp<%=@comp_id%>">
</turbo-stream>

app/views/complaint/history.html.erb
<div style="margin-left: 50px">
    <h2><%= t('header.history_complaint') %></h2> <br>
    <% if Complaint.find_by(user_id: current_user.id).present? %>
        <ol>
        <% Complaint.where(user: current_user).each do |comp|%>
            <div class="card" style="font-size:20px; width:700px">
                <div class="card-body">            
                    <p><%=comp.created_at.strftime("%d.%m.%Y") + ' ' + comp.created_at.strftime("%H:%M")%></p>
                    <p style="margin-left: 50px"><strong>Тема: </strong><%=comp.theme%></p>
                    <p style="margin-left: 50px"><strong>Статус жалобы: </strong><%=t("complaint.new.#{comp.status}")%></p>
                    <p style="margin-left: 50px"><strong>Жалоба: </strong><%=comp.message%></p>
                    <% if comp.response.present? %>
                        <br>
                        <p><%=comp.updated_at.strftime("%d.%m.%Y") + ' ' + comp.updated_at.strftime("%H:%M")%></p>
                        <p style="margin-left: 50px;"> <strong>Ответ: </strong><%=comp.response%></p>   
                    <% end %>   
                </div>
            </div>
            <br>
        <% end %>
        </ol>
    <% else %>
        <h3> Нет истории жалоб </h3>   
    <% end %>
</div>

app/views/complaint/new.html.erb
<div style="margin-left: 50px">
    <h2><%= t('header.new_complaint') %></h2> <br>
    <%= form_with url: complaint_add_path do |f|%>
        <div style="width:700px">
            <%= f.text_field :theme, class: "form-control", placeholder: t('complaint.new.theme'), autofocus: true %>
        </div>
        <div style="width:700px">
            <%= f.text_area :problem, :rows => 12, class: "form-control", placeholder: t('complaint.new.problem'), autofocus: true, id: 'problem' %>
        </div>
        <div>
            <%= f.submit t('complaint.new.send'), class: 'btn btn-primary'%>
        </div>
    <% end %>
</div>

app/views/complaint/reply.turbo_stream.erb
<turbo-stream action="remove" target="comp<%=@comp_id%>">
</turbo-stream>